spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
        keep-alive-time-unit: SECONDS
        keep-alive-time: 60
